### ISSUE TITLE
Get Motor Running using Arduino

### ISSUE THREAD

**Issue by abrahamhadaf** [abrahamhadaf/Jetson-Autonomous-Car#1]
Having trouble getting the motor to run. Need to debug the issues that prevent it from running.

**Comment by abrahamhadaf** [comment]
Need RC controller for calibration of the motor and ESC

**Comment by sammdemissie** [comment]
We need to first enable serial port communication between Jetson and Arduino(Maybe installing additional dependancies i.e Pyserial). Then, test on simple script to validate communication

**Comment by abrahamhadaf** [comment]
Motor runs using adafruit
